### ISSUE TITLE
Can't update column Desktop column to not set

### ISSUE THREAD

**Issue by SebastianDaehnrich** [laxap/bootstrap_grids#8]
I wan't to update the Desktop column to not set. But this is not working with gridelements 7.0.5.
I'm running typo3 7.4.6.

**Comment by SventB** [comment]
I'm wondering about this, too. It should be "mobile first": If a value for "Small devices" is set, all other columns could be set to "not set". That means, "Small devices" should be the tab which is default and which is placed on the left side.
In addition, the order is proper if the tabs start with "Small devices" and end with "Large devices".

**Comment by laxap** [comment]
@SebastianDaehnrich  - it's fixed in version 1.3.0. Tested on TYPO3 7.6.x.

**Comment by SventB** [comment]
It's still not "mobile first" and still no proper order: tab "Desktop" ist first, "Small devices" is second, why?

**Comment by SventB** [comment]
Ok, now it is, thank you :)
